AUTH0_DOMAIN = "dev-qwn3runpmc616as6.us.auth0.com"
AUTH0_CLIENT_ID = "XvRZKwcHlcToRYGMMwnZiNjLnNzJmUmU"
AUTH0_CLIENT_SECRET = "y7Sn91jH3sR1seU5uWPJAM89BSmS-pXfPQPcfDLzt_K3Cu2fk-D0vzYnA2sE2lah"
AUTH0_CALLBACK_URL = "https://cubesimprov2-lt6hcgkvpdvygnwbktyqdg.streamlit.app"

